name: Deploy

on:
  pull_request_target:
      branches: main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to production
        run: |
          # Add your deployment script here
          echo "Deploying to production"

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/thomasphorton-github/branch-protection/deployments \
            -f ref='topic-branch' \
            -f payload='{ "deploy": "migrate" }' \
            -f description='Deploy request from hubot' 
    environment:
      name: production
      url: https://example.com
